#!/bin/bash

##
#  cor - container-over-ramdisk - at lack of a better name
#  Copyright 2016 Jeroen <Jayfrown @ github.com>

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.



#  A clean, robust implementation of this concept might
#  warrant support at the lower levels - LXD or even LXC
#
#  Do not expect this script to just work on your system
#  You're welcome to tinker with it, of course

# include functions
include_dir="${BASH_SOURCE%/*}/func"
. "${include_dir}/_main"
. "${include_dir}/_cor"



#  OverlayFS allows multiple containers to concurrently
#  share a single [read-only] rootfs (lower), storing their respective
#  changes in their 'persistent_storage' (upper) directories.


#  assume the following local configuration
#  - LXD - Canonicals LXC daemon
#		 - images:gentoo/current/amd64 copied locally, auto-update, aliased 'gentoo'
#		 - container 'gentoo' with an emptied rootfs at ${lower_rootfs}, no overlays
#
#  - ${lower_rootfs} to be on tmpfs and in fstab (optional, but highly recommended)
#	 !! If you don't, the only gain is in diskspace, by reusing the base rootfs
#	 !! If you do, the whole base-system is always fully in-memory.
#

#  NOTES
#  - Definitely not production material
#  - Every rebuild (reboot) == potential upgrade in base, as the image aliased 'gentoo' is auto-updated
#  - http://frightanic.com/goodies_content/docker-names.php -- because lxc clone needs a target name


# main()
lxdBase="/var/lib/lxd"
containerBase="${lxdBase}/containers"
lower_rootfs="${containerBase}/gentoo/rootfs"

generatedName="$(curl -L "http://frightanic.com/goodies_content/docker-names.php" 2>/dev/null |tr "_" "-")"

# check for empty base-system
if [[ -d ${lower_rootfs}/usr ]]; then
	empty_rootfs="false"
else
	empty_rootfs="true"
fi

# action
case $1 in

	# show a help message
	help)
		show-helpmsg ${2}
		;;

	# rebuild the base-system rootfs (lower)
	rebuild)
		if [[ ${empty_rootfs} = "true" ]]; then

			confirm "rebuild base-system" && rebuild-rootfs
		else

			bMsg "non-empty rootfs, not rebuilding"
			exit 1
		fi
		;;

	# remount overlayfs for container
	remount)
		containerName="containerName"
		[[ $2 ]] && containerName="${2}"

		if [[ "${containerName}" != "gentoo" && "${containerName}" != "empty" ]]; then
			if [[ ${empty_rootfs} = "false" ]]; then

				confirm "remount overlay" && echo "would remount $containerName" #prep-container && overlay
			else

				bMsg "empty base-system, please rebuild"
				exit 1
			fi
		else

			bMsg "container is part of overlay structure: ${containerName}"
			exit
		fi
		;;

	# new container over base-system
	create)
		containerName="${generatedName}"
		[[ $2 ]] && containerName="${2}"

		if [[ ${empty_rootfs} = "false" ]]; then

			confirm "new container ${containerName}" && empty-container && prep-container && overlay
		else

			bMsg "empty base-system, please rebuild"
			exit 1
		fi
		;;

	*)
		gMsg "usage: ${prog} action $(magenta [containerName])"
		echo
		gMsg "$(red help) | $(red create) | $(red remount) | $(red rebuild)"
		;;
esac